services:
  - type: web
    name: github-to-exe
    runtime: python3
    buildCommand: pip install -r backend/requirements.txt && pip install pyinstaller
    startCommand: python server.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 5001
    scaling:
      minInstances: 1
      maxInstances: 1